CREATE TABLE ZSE (
        DIONICA TEXT,
        DATUM TEXT,
        PRVA NUMERIC,
        ZADNJA NUMERIC,
        NAJVISA NUMERIC,
        NAJNIZA NUMERIC,
        PROSJECNA NUMERIC,
        PROMJENA NUMERIC,
        KOLICINA NUMERIC,
        PROMET NUMERIC,
        PRIMARY KEY(DIONICA,DATUM)
);
